<footer id="footer">
  <div class="row clearfix">
    <div id="footer-utility-links">
      <ul class="menu gt-footer-utility-links">
        <li class="first"><a href="/" title="" class="active">About This Site</a></li>
        <li class="last"><a href="/" title="" class="active">Contact Us</a></li>
      </ul>
      <ul class="menu custom-links-included">
        <li><a href="http://www.gatech.edu/emergency/">Emergency Information</a></li>
        <li><a href="http://www.gatech.edu/legal/">Legal &amp; Privacy Information</a></li>
        <li><a href="http://www.gatech.edu/accountability/">Accountability</a></li>
        <li><a href="http://www.careers.gatech.edu">Employment</a></li>
        <li class="site-login last"><a href="/user">Login</a></li>
       </ul> 
    </div>
    <div id="footer-logo">
      <a href="http://www.gatech.edu/"><img alt="Georgia Tech" src="/images/logos/gt-logo-footer.png" ></a>
      <p>&copy; 2013 Georgia Institute of Technology</p>
    </div>
  </div>
</footer><!-- /footer --> 