<section id="superfooter">
  <div class="row clearfix">
  
    <div class="superfooter-resource-links" id="gt-default-resource-links">
      <h4 class="title">Georgia Tech Resources</h4>
      <ul class="menu" id="gt-default-resources">
        <li><a href="http://www.gatech.edu/departments">Offices &amp; Departments</a></li>
        <li><a href="http://www.news.gatech.edu">Newsroom</a></li>
        <li><a href="http://www.calendar.gatech.edu">Campus Calendar</a></li>
        <li><a href="http://www.specialevents.gatech.edu">Special Events</a></li>
        <li><a href="http://www.greenbuzz.gatech.edu">GreenBuzz</a></li>
        <li><a href="http://www.comm.gatech.edu">Institute Communications</a></li>
        <li><span class="nolink">Visitor Resources</span></li>
        <li><a href="http://www.admission.gatech.edu/visit">Campus Visits</a></li>
        <li><a href="http://www.gatechhotel.com">Georgia Tech Hotel &amp; Conference Center</a></li>
        <li><a href="http://www.glc.gatech.edu">Georgia Tech Global Learning Center</a></li>
        <li><a href="http://www.pts.gatech.edu/visitors/Pages/default.aspx">Visitor Parking Information</a></li>
        <li><a href="http://www.admission.gatech.edu/visit/directions-and-parking">Directions to Campus</a></li>
        <li><a href="http://www.lawn.gatech.edu/help/GTvisitor.html">GTvisitor Wireless Network Information</a></li>
        <li><a href="http://www.gatech.bncollege.com">Barnes &amp; Noble at Georgia Tech</a></li>
        <li><a href="http://www.ferstcenter.gatech.edu">Robert Ferst Center for the Arts</a></li>
        <li><a href="http://www.ipst.gatech.edu/amp">Robert C. Williams Paper Museum</a></li>
      </ul>
    </div>
    
    <div class="superfooter-resource-links" id="gt-footer-links-1">
      <h4 class="title">Colleges &amp; Campuses</h4>
      <ul class="menu"><li class="first"><span title="" class="nolink">Colleges</span></li>
        <li><a href="http://www.coa.gatech.edu" title="">College of Architecture</a></li>
        <li><a href="http://www.cc.gatech.edu" title="">College of Computing</a></li>
        <li><a href="http://www.coe.gatech.edu" title="">College of Engineering</a></li>
        <li><a href="http://www.cos.gatech.edu" title="">College of Sciences</a></li>
        <li><a href="http://www.iac.gatech.edu" title="">Ivan Allen College of Liberal Arts</a></li>
        <li><a href="http://www.scheller.gatech.edu" title="">Scheller College of Business</a></li>
        <li><span title="" class="nolink">Campuses</span></li>
        <li><a href="http://www.savannah.gatech.edu" title="">Savannah</a></li>
        <li><a href="http://www.lorraine.gatech.edu" title="">France</a></li>
        <li><a href="http://tip.gatech.edu" title="">Costa Rica</a></li>
        <li><a href="http://www.gtri.gatech.edu/gtireland" title="">Ireland</a></li>
        <li><a href="http://pku.bme.gatech.edu" title="">Peking University Joint Degree Program</a></li>
        <li><a href="http:/www.shanghai.gatech.edu" title="">Shanghai</a></li>
        <li><a href="http://www.tliap.nus.edu.sg" title="">Singapore</a></li>
      </ul>
    </div>
    
    <div class="superfooter-resource-links"  id="gt-footer-links-2">
      <h4 class="title">Student &amp; Parent Resources</h4>
      <ul class="menu">
        <li class="first"><span title="" class="nolink">Student Resources</span></li>
        <li><a href="http://www.gatech.edu/admissions/" title="">Apply</a></li>
        <li><a href="http://www.buzzcard.gatech.edu" title="">BuzzCard</a></li>
        <li><a href="http://buzzport.gatech.edu" title="">BuzzPort</a></li>
        <li><a href="http://www.career.gatech.edu" title="">Career Services</a></li>
        <li><a href="http://www.profpractice.gatech.edu" title="">Co-op &amp; Internships</a></li>
        <li><a href="http://www.commencement.gatech.edu" title="">Commencement</a></li>
        <li><a href="http://www.finaid.gatech.edu/content/application-process" title="">Financial Aid</a></li>
        <li><a href="http://www.library.gatech.edu" title="">Library</a></li>
        <li><a href="http://www.studentaffairs.gatech.edu" title="">Student Affairs</a></li>
        <li><a href="http://www.calendar.gatech.edu/student" title="">Student Calendar</a></li>
        <li><a href="http://www.oie.gatech.edu/study-abroad" title="">Study Abroad</a></li>
        <li><a href="http://t-square.gatech.edu" title="">T-Square</a></li>
        <li><span title="" class="nolink">Parent Resources</span></li>
        <li class="last"><a href="http://www.parents.gatech.edu" title="">Parents Program</a></li>
      </ul>
    </div>
        
    <div class="superfooter-resource-links" id="gt-footer-links-3">
      <h4 class="title">Faculty, Staff &amp; Alumni Resources</h4>
      <ul class="menu">
        <li class="first"><span title="" class="nolink">Faculty &amp; Staff</span></li>
        <li><a href="http://www.advising.gatech.edu" title="">Advising &amp; Teaching</a></li>
        <li><a href="http://www.facultygovernance.gatech.edu" title="">Faculty Governance</a></li>
        <li><a href="http://www.careers.gatech.edu" title="">Faculty Hiring</a></li>
        <li><a href="http://www.provost.gatech.edu" title="">Office of the Provost</a></li>
        <li><a href="http://techworks.gatech.edu" title="">TechWorks</a></li>
        <li><span title="" class="nolink">Alumni</span></li>
        <li><a href="http://www.gtalumni.org" title="">Alumni Association</a></li>
        <li><a href="http://www.gatech.edu/economic-development" title="">Economic Development</a></li>
        <li><a href="http://www.gatech.edu/employers" title="">Employers &amp; Industry</a></li>
        <li><a href="http://www.innovate.gatech.edu" title="">Enterprise Innovation Institute (EI2)</a></li>
        <li><a href="http://www.gtri.gatech.edu" title="">Georgia Tech Research Institute (GTRI)</a></li>
        <li><a href="http://www.gov.gatech.edu" title="">Government Partners</a></li>
      </ul>
    </div>
    
    <div id="street-address-info">
      <a href="http://www.map.gatech.edu"><img alt="Map of Georgia Tech" src="/images/gt-map-image-default.jpg" /></a>
      <div class="street-address">
        <p>Georgia Institue of Technology<br />
        North Avenue, Atlanta, GA 30332<br />
        Phone: 404-894-2000</p>
      </div>
    </div>
    
  </div>
</section><!-- /superfooter -->